### ISSUE TITLE
Locked huncwot version in template package.json

### ISSUE THREAD

**Issue by hasparus** [huncwotjs/huncwot#54]
Should this be locked?
https://github.com/huncwotjs/huncwot/blob/7b5c9553cbdc361d3399a3a1a3501f6f8f39819a/template/base/package.json#L7

I have installed huncwot globally today. My version is 0.53.1.
```
~/workspace/huncwot-test took 5s 
⇝  huncwot --version
No YAML parser loaded.  Suggest adding js-yaml dependency to your package.json file.
0.53.1
```

Yet, the project I have just initialized with `huncwot new` has version 0.53.0 locked.
I just tried to start a PR to move @zerollup/ts-transform-paths to dependencies 😅

**Comment by hasparus** [comment]
Yup, it generates new project with the previous version.
Shoud the version in template/package.json be updated by in a prerelease step?
(Regardless if it's locked or not)

```
workspace/huncwot-test/huncwot-test-2 
⇝  cat package.json 
{
  "name": "huncwot-test-2",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "stmux -w always -e ERROR -m beep,system -- [ -t 'Client' 'huncwot client' .. -t 'Server' 'huncwot server' ]"
  },
  "dependencies": {
    "huncwot": "0.53.0"
  },
```

**Comment by zaiste** [comment]
@hasparus Yes! That's an excellent catch

I also wonder about this `js-yaml` dependency. I didn't have that. I believe it should be included in Huncwot as well. It seems I have it installed globally here.

**Comment by hasparus** [comment]
Are you open for contributions (i.e. node oneliner in package.json prepublish script) on this?
I'd also add CONTRIBUTING.md we've spoken about in https://github.com/huncwotjs/huncwot/pull/55.

**Comment by zaiste** [comment]
@hasparus Yes, absolutely for both!
