### ISSUE TITLE
yarn dependency

### ISSUE THREAD

**Issue by emilos** [huncwotjs/huncwot#60]
Just a quick question, does it still make sense to use yarn? npm got better over the years. Or maybe that's just an error in the docs?

```
You also need to install yarn.
```

**Comment by zaiste** [comment]
@emilos Yes, that's an error in the docs. I've came to the same conclusion and removed `yarn` at some point in the past. `npm` is good enough and there is less moving parts.

**Comment by zaiste** [comment]
@emilos fixed in d0747c4d2a57cb3f1fc9342374f8f370f813dff3
