### ISSUE TITLE
npm run lint

### ISSUE THREAD

**Issue by emilos** [huncwotjs/huncwot#61]
It would be nice to have a `npm run lint` script in package.json that would let you to use the default linter/prettifier. Right now it's not obvious how to run it.

**Comment by emilos** [comment]
Step 1: install

```
npm install standard
```

Step 2: add lint to package.json (scripts section)

```
"lint": "standard"
```

Step 3: autofixes

```
npm run lint -- --fix
```

Step 4: manual fixes

**Comment by zaiste** [comment]
@emilos I've just realized I've configured here `eslint` with `eslint:recommended`. Would that be enough for starters ?

**Comment by emilos** [comment]
anything works for now I guess

**Comment by zaiste** [comment]
@emilos I've improved the current ESLint configuration along with Prettier, but for some strange reason the `singleQuote` option is not being taken account. The `explainer.js` line `20` is a good example of that. I'm not sure how to resolve it.

**Comment by emilos** [comment]
@zaiste I'm not sure, it's probably not worth investigating now :) I'll just close this given it's much better now
