### ISSUE TITLE
Just installed and trying to start the server getting error.

### ISSUE THREAD

**Issue by kalaikt** [huncwotjs/huncwot#88]
Error connect ECONNREFUSED 127.0.0.1:5432
  Explanation 
  It looks like you haven't started your database server.

  Stack trace
  - TCPConnectWrap.afterConnect [as oncomplete]
    net.js:1137

**Comment by zaiste** [comment]
@kalaikt You need to start a PostgreSQL instance. I should've been more clear in the docs. I'm working on it.

**Comment by kalaikt** [comment]
thanks, where to update the DB username and password?
 Error password authentication failed for user "root"
  Explanation 
  (missing)

**Comment by zaiste** [comment]
@kalaikt You can specify your DB connection settings in `config/default.yml`.

**Comment by kalaikt** [comment]
yes, I have updated those but still throws below error, do you have any sample file.

Error password authentication failed for user "root"
Explanation
(missing)

**Comment by zaiste** [comment]
@kalaikt Could you try connecting with `psql` using the same credentials ?

**Comment by kalaikt** [comment]
`psql` working

**Comment by zaiste** [comment]
@kalaikt can you share your `psql` command along with the content of your `default.yml` ?

**Comment by kalaikt** [comment]
psql
-----

Server [localhost]: 
Database [postgres]: 
Port [5432]: 
Username [postgres]: 
Password for user postgres: 
psql (12.2)
Type "help" for help.

postgres=# SELECT VERSION();
                                                          version                                                           
----------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 12.2 on x86_64-apple-darwin, compiled by Apple LLVM version 6.0 (clang-600.0.54) (based on LLVM 3.5svn), 64-bit
(1 row)

default.yml
-----------

db:
  database: "postgres"
  username: "postgres"
  password: "*******"

deploy:
  server:
    src: .
    dest: "YOUR DESTINATION"
    delete: true
    exclude:
      - dist
      - node_modules
      - .git
      - static/upload
      - config/default.yaml
  client:
    src: dist/
    dest: "YOUR DESTINATION"
    delete: true

**Comment by zaiste** [comment]
@kalaikt did it work?

**Comment by kalaikt** [comment]
no its not working. let me try in windows machine and let you know. Thanks for your response.

**Comment by zaiste** [comment]
@kalaikt please re-open the issue if you still have the problem

**Comment by MuzickMan80** [comment]
Hello, I am also seeing this issue.  I have tried modifying the default.yml file as above, however it seems to ignore the username specified in the config/default.yml file and instead uses my windows username.

**Comment by FDiskas** [comment]
> @kalaikt You can specify your DB connection settings in `config/default.yml`.

I would like this to be already present with some defaults. As a new joiner - I also started and got error.
```
  Database  Not OK
     Error  password authentication failed for user "vkuciauskas"
    Reason  (missing)
 > error: Cannot start service: Host version "0.8.30" does not match binary version "0.8.12"
```
![image](https://user-images.githubusercontent.com/468006/103811054-f73f3b00-5064-11eb-8699-d0e92b6a7a12.png)

**Comment by jiapei100** [comment]
> @kalaikt under the `db` section could you add the `host` field as following ?
> 
> ```yaml
> db:
>   database: "postgres"
>   username: "postgres"
>   password: "*******"
>   host: localhost
> ```
> 
> Be sure to have the same indentation.
> 
> As a general rule, it's not good to use the `postgres` user. I suggest you create another user using the PostgreSQL bult-in `createuser` command. But first let's try if the setup above works for you.

Hi, @zaiste  Thank you for your hint. But now, there is **NO** `default.html`, but the file `config/default.json` is there, and its contents:

```json
{
  "deploy": {
    "delete": false,
    "dest": "DESTINATION",
    "exclude": [
      "dist",
      "node_modules",
      ".git",
      "static/upload",
      "config/default.json"
    ],
    "src": "."
  },
  "commands": {
    "docker": {
      "build": "docker build -f ./config/docker/Dockerfile --tag kretes:dlppico.com",
      "start": "docker run -p 5544 --name dlppico.com kretes:dlppico.com",
      "port": "docker inspect --format='{{(index (index .NetworkSettings.Ports \"5544/tcp\") 0).HostPort}}' dlppico.com"
    }
  }
}
```

So, how and where to add your code snnpit:
```json
db:
  database: "postgres"
  username: "postgres"
  password: "*******"
  host: localhost
```

Thank you very much...

**Comment by jiapei100** [comment]
@kalaikt 

Got it: [https://kretes.dev/docs/tutorial/database-setup/ ](https://kretes.dev/docs/tutorial/database-setup/)
Thank you...
